#!/bin/bash

DEV_CFG='dev.cfg'

function install
{
    pip install -r requirements.txt
}

function foreman
{
    env APP_CONFIG=$DEV_CFG foreman start
}

function runserver
{
    env APP_CONFIG=$DEV_CFG python app.py
}

eval $BASH_ARGV
